sudo: required

services:
  - docker

before_install:
  - docker build -t tuudik/bookstack:$(cat VERSION) .

install:
  - docker-compose up -d 
  - sleep 30

script:
  - curl -sSf http://localhost:8080/login > /dev/null

after_failure:
  - timeout 3s docker-compose logs bookstack mysql
